apiVersion: v1
kind: Service
metadata:
  name: bridge
  namespace: cloudops-bridge
  labels:
    app.kubernetes.io/name: bridge
    app.kubernetes.io/part-of: cloudops-bridge
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: bridge
  ports:
    - name: http
      port: 8081
      targetPort: http
