#!/usr/bin/env bash
# Regenerate the ConfigMaps from the source-of-truth files.
#
#   service-catalog/*.yaml  ->  kubernetes/config/service-catalog-configmap.yaml
#   runbooks/*.md           ->  kubernetes/config/runbooks-configmap.yaml
#   dashboards/*.json       ->  kubernetes/monitoring/grafana/dashboard-configmap.yaml
#   loadtest/*.py           ->  loadtest/loadgen-configmap.yaml
#
# Never edit the generated files by hand. tests/test_kubernetes_config.py fails
# if they drift from the sources. Run from anywhere:
#   ./kubernetes/generate-configmaps.sh

set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"

generate() {
  local ns="$1" name="$2" source_dir="$3" pattern="$4" out_file="$5"
  local args=()
  for f in "$source_dir"/$pattern; do
    args+=("--from-file=$f")
  done
  {
    echo "# GENERATED by kubernetes/generate-configmaps.sh from ${source_dir#"$ROOT"/}/ - do not edit."
    # Drop the "creationTimestamp: null" some kubectl versions emit; otherwise
    # every apply reports "configured" for a no-op change.
    kubectl create configmap "$name" --namespace "$ns" "${args[@]}" \
      --dry-run=client -o yaml | grep -v '^  creationTimestamp: null$'
  } > "$out_file"
  echo "wrote ${out_file#"$ROOT"/}"
}

generate cloudops-bridge service-catalog    "$ROOT/service-catalog" "*.yaml" "$ROOT/kubernetes/config/service-catalog-configmap.yaml"
generate cloudops-bridge runbooks           "$ROOT/runbooks"        "*.md"   "$ROOT/kubernetes/config/runbooks-configmap.yaml"
generate monitoring      grafana-dashboards "$ROOT/dashboards"      "*.json" "$ROOT/kubernetes/monitoring/grafana/dashboard-configmap.yaml"
generate cloudops-bridge loadgen-script      "$ROOT/loadtest"        "*.py"   "$ROOT/loadtest/loadgen-configmap.yaml"
