#!/usr/bin/env bash
# Regenerate the ConfigMaps from the source-of-truth files.
#
#   service-catalog/*.yaml  ->  kubernetes/config/service-catalog-configmap.yaml
#   runbooks/*.md           ->  kubernetes/config/runbooks-configmap.yaml
#
# Never edit the generated files by hand. tests/test_kubernetes_config.py fails
# if they drift from the sources. Run from anywhere:
#   ./kubernetes/generate-configmaps.sh

set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$ROOT/kubernetes/config"
NS=cloudops-bridge

generate() {
  local name="$1" source_dir="$2" pattern="$3" out_file="$4"
  local args=()
  for f in "$source_dir"/$pattern; do
    args+=("--from-file=$f")
  done
  {
    echo "# GENERATED by kubernetes/generate-configmaps.sh from ${source_dir#"$ROOT"/}/ - do not edit."
    # Drop the "creationTimestamp: null" some kubectl versions emit; otherwise
    # every apply reports "configured" for a no-op change.
    kubectl create configmap "$name" --namespace "$NS" "${args[@]}" \
      --dry-run=client -o yaml | grep -v '^  creationTimestamp: null$'
  } > "$out_file"
  echo "wrote ${out_file#"$ROOT"/}"
}

generate service-catalog "$ROOT/service-catalog" "*.yaml" "$OUT/service-catalog-configmap.yaml"
generate runbooks        "$ROOT/runbooks"        "*.md"   "$OUT/runbooks-configmap.yaml"
